// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_partial_products8;
    reg [7:0] a;
    reg [7:0] b;
    wire [63:0] d_pp;
    wire [63:0] g_pp;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    partial_products8 dut(
        .a(a),
        .b(b),
        .pp(d_pp)
    );

    gold_partial_products8 gut(
        .a(a),
        .b(b),
        .pp(g_pp)
    );

    initial begin
        seed = 32'd66110;
        a = 0;
        b = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); a = r[7:0];
            r = $random(seed); b = r[7:0];
            #10;
            if ({d_pp} !== {g_pp}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH partial_products8 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS partial_products8 lockstep (500 vectors)");
        else $display("FAIL partial_products8: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
