// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_GPU;
    reg clk;
    reg reset;
    reg gpu_we;
    reg [3:0] gpu_addr;
    reg [31:0] gpu_wdata;
    reg screen_ready;
    wire [31:0] d_gpu_rdata;
    wire [31:0] g_gpu_rdata;
    wire d_frame_start;
    wire g_frame_start;
    wire d_frame_done;
    wire g_frame_done;
    wire [7:0] d_scr_w;
    wire [7:0] g_scr_w;
    wire [7:0] d_scr_h;
    wire [7:0] g_scr_h;
    wire [1:0] d_scr_ctype;
    wire [1:0] g_scr_ctype;
    wire d_enable;
    wire g_enable;
    wire d_fill;
    wire g_fill;
    wire d_mono_valid;
    wire g_mono_valid;
    wire [7:0] d_mono_y;
    wire [7:0] g_mono_y;
    wire [63:0] d_mono_s0;
    wire [63:0] g_mono_s0;
    wire [63:0] d_mono_s1;
    wire [63:0] g_mono_s1;
    wire [63:0] d_mono_s2;
    wire [63:0] g_mono_s2;
    wire [63:0] d_mono_s3;
    wire [63:0] g_mono_s3;
    wire d_px_valid;
    wire g_px_valid;
    wire [4:0] d_px_x;
    wire [4:0] g_px_x;
    wire [4:0] d_px_y;
    wire [4:0] g_px_y;
    wire [3:0] d_px_mux;
    wire [3:0] g_px_mux;
    wire [23:0] d_px_rgb;
    wire [23:0] g_px_rgb;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    GPU dut(
        .clk(clk),
        .reset(reset),
        .gpu_we(gpu_we),
        .gpu_addr(gpu_addr),
        .gpu_wdata(gpu_wdata),
        .screen_ready(screen_ready),
        .gpu_rdata(d_gpu_rdata),
        .frame_start(d_frame_start),
        .frame_done(d_frame_done),
        .scr_w(d_scr_w),
        .scr_h(d_scr_h),
        .scr_ctype(d_scr_ctype),
        .enable(d_enable),
        .fill(d_fill),
        .mono_valid(d_mono_valid),
        .mono_y(d_mono_y),
        .mono_s0(d_mono_s0),
        .mono_s1(d_mono_s1),
        .mono_s2(d_mono_s2),
        .mono_s3(d_mono_s3),
        .px_valid(d_px_valid),
        .px_x(d_px_x),
        .px_y(d_px_y),
        .px_mux(d_px_mux),
        .px_rgb(d_px_rgb)
    );

    gold_GPU gut(
        .clk(clk),
        .reset(reset),
        .gpu_we(gpu_we),
        .gpu_addr(gpu_addr),
        .gpu_wdata(gpu_wdata),
        .screen_ready(screen_ready),
        .gpu_rdata(g_gpu_rdata),
        .frame_start(g_frame_start),
        .frame_done(g_frame_done),
        .scr_w(g_scr_w),
        .scr_h(g_scr_h),
        .scr_ctype(g_scr_ctype),
        .enable(g_enable),
        .fill(g_fill),
        .mono_valid(g_mono_valid),
        .mono_y(g_mono_y),
        .mono_s0(g_mono_s0),
        .mono_s1(g_mono_s1),
        .mono_s2(g_mono_s2),
        .mono_s3(g_mono_s3),
        .px_valid(g_px_valid),
        .px_x(g_px_x),
        .px_y(g_px_y),
        .px_mux(g_px_mux),
        .px_rgb(g_px_rgb)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd82681;
        gpu_we = 0;
        gpu_addr = 0;
        gpu_wdata = 0;
        screen_ready = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); gpu_we = r[0:0];
            r = $random(seed); gpu_addr = r[3:0];
            r = $random(seed); gpu_wdata = r[31:0];
            r = $random(seed); screen_ready = r[0:0];
            @(posedge clk); #1;
            if ({d_gpu_rdata, d_frame_start, d_frame_done, d_scr_w, d_scr_h, d_scr_ctype, d_enable, d_fill, d_mono_valid, d_mono_y, d_mono_s0, d_mono_s1, d_mono_s2, d_mono_s3, d_px_valid, d_px_x, d_px_y, d_px_mux, d_px_rgb} !== {g_gpu_rdata, g_frame_start, g_frame_done, g_scr_w, g_scr_h, g_scr_ctype, g_enable, g_fill, g_mono_valid, g_mono_y, g_mono_s0, g_mono_s1, g_mono_s2, g_mono_s3, g_px_valid, g_px_x, g_px_y, g_px_mux, g_px_rgb}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH GPU @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS GPU lockstep (2000 cycles)");
        else $display("FAIL GPU: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
