// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_pipelined32;
    reg clk;
    reg reset;
    reg gpu_we;
    reg [3:0] gpu_addr;
    reg [31:0] gpu_wdata;
    reg ppln_point;
    reg ppln_line;
    reg ppln_rect;
    reg screen_ready;
    wire [31:0] d_gpu_rdata;
    wire [31:0] g_gpu_rdata;
    wire d_frame_start;
    wire g_frame_start;
    wire d_frame_done;
    wire g_frame_done;
    wire d_enable;
    wire g_enable;
    wire d_fill;
    wire g_fill;
    wire d_px_valid;
    wire g_px_valid;
    wire [4:0] d_px_x;
    wire [4:0] g_px_x;
    wire [4:0] d_px_y;
    wire [4:0] g_px_y;
    wire [23:0] d_px_rgb;
    wire [23:0] g_px_rgb;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    gpu_pipelined32 dut(
        .clk(clk),
        .reset(reset),
        .gpu_we(gpu_we),
        .gpu_addr(gpu_addr),
        .gpu_wdata(gpu_wdata),
        .ppln_point(ppln_point),
        .ppln_line(ppln_line),
        .ppln_rect(ppln_rect),
        .screen_ready(screen_ready),
        .gpu_rdata(d_gpu_rdata),
        .frame_start(d_frame_start),
        .frame_done(d_frame_done),
        .enable(d_enable),
        .fill(d_fill),
        .px_valid(d_px_valid),
        .px_x(d_px_x),
        .px_y(d_px_y),
        .px_rgb(d_px_rgb)
    );

    gold_gpu_pipelined32 gut(
        .clk(clk),
        .reset(reset),
        .gpu_we(gpu_we),
        .gpu_addr(gpu_addr),
        .gpu_wdata(gpu_wdata),
        .ppln_point(ppln_point),
        .ppln_line(ppln_line),
        .ppln_rect(ppln_rect),
        .screen_ready(screen_ready),
        .gpu_rdata(g_gpu_rdata),
        .frame_start(g_frame_start),
        .frame_done(g_frame_done),
        .enable(g_enable),
        .fill(g_fill),
        .px_valid(g_px_valid),
        .px_x(g_px_x),
        .px_y(g_px_y),
        .px_rgb(g_px_rgb)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd353;
        gpu_we = 0;
        gpu_addr = 0;
        gpu_wdata = 0;
        ppln_point = 0;
        ppln_line = 0;
        ppln_rect = 0;
        screen_ready = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); gpu_we = r[0:0];
            r = $random(seed); gpu_addr = r[3:0];
            r = $random(seed); gpu_wdata = r[31:0];
            r = $random(seed); ppln_point = r[0:0];
            r = $random(seed); ppln_line = r[0:0];
            r = $random(seed); ppln_rect = r[0:0];
            r = $random(seed); screen_ready = r[0:0];
            @(posedge clk); #1;
            if ({d_gpu_rdata, d_frame_start, d_frame_done, d_enable, d_fill, d_px_valid, d_px_x, d_px_y, d_px_rgb} !== {g_gpu_rdata, g_frame_start, g_frame_done, g_enable, g_fill, g_px_valid, g_px_x, g_px_y, g_px_rgb}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_pipelined32 @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_pipelined32 lockstep (2000 cycles)");
        else $display("FAIL gpu_pipelined32: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
