// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_frame_crc32;
    reg clk;
    reg reset;
    reg px_valid;
    reg accept;
    reg [7:0] px_x;
    reg [7:0] px_y;
    reg [23:0] px_rgb;
    reg frame_start;
    reg frame_done;
    wire [31:0] d_frame_sig;
    wire [31:0] g_frame_sig;
    wire d_sig_valid;
    wire g_sig_valid;
    wire [15:0] d_frame_index;
    wire [15:0] g_frame_index;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    gpu_frame_crc32 dut(
        .clk(clk),
        .reset(reset),
        .px_valid(px_valid),
        .accept(accept),
        .px_x(px_x),
        .px_y(px_y),
        .px_rgb(px_rgb),
        .frame_start(frame_start),
        .frame_done(frame_done),
        .frame_sig(d_frame_sig),
        .sig_valid(d_sig_valid),
        .frame_index(d_frame_index)
    );

    gold_gpu_frame_crc32 gut(
        .clk(clk),
        .reset(reset),
        .px_valid(px_valid),
        .accept(accept),
        .px_x(px_x),
        .px_y(px_y),
        .px_rgb(px_rgb),
        .frame_start(frame_start),
        .frame_done(frame_done),
        .frame_sig(g_frame_sig),
        .sig_valid(g_sig_valid),
        .frame_index(g_frame_index)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd72482;
        px_valid = 0;
        accept = 0;
        px_x = 0;
        px_y = 0;
        px_rgb = 0;
        frame_start = 0;
        frame_done = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); px_valid = r[0:0];
            r = $random(seed); accept = r[0:0];
            r = $random(seed); px_x = r[7:0];
            r = $random(seed); px_y = r[7:0];
            r = $random(seed); px_rgb = r[23:0];
            r = $random(seed); frame_start = r[0:0];
            r = $random(seed); frame_done = r[0:0];
            @(posedge clk); #1;
            if ({d_frame_sig, d_sig_valid, d_frame_index} !== {g_frame_sig, g_sig_valid, g_frame_index}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_frame_crc32 @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_frame_crc32 lockstep (2000 cycles)");
        else $display("FAIL gpu_frame_crc32: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
