// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_interp_fetch_switch32;
    reg mode;
    reg [31:0] native_instr;
    reg [31:0] xlat_instr;
    reg xlat_trap;
    wire [31:0] d_host_instr;
    wire [31:0] g_host_instr;
    wire d_trap_out;
    wire g_trap_out;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    interp_fetch_switch32 dut(
        .mode(mode),
        .native_instr(native_instr),
        .xlat_instr(xlat_instr),
        .xlat_trap(xlat_trap),
        .host_instr(d_host_instr),
        .trap_out(d_trap_out)
    );

    gold_interp_fetch_switch32 gut(
        .mode(mode),
        .native_instr(native_instr),
        .xlat_instr(xlat_instr),
        .xlat_trap(xlat_trap),
        .host_instr(g_host_instr),
        .trap_out(g_trap_out)
    );

    initial begin
        seed = 32'd55165;
        mode = 0;
        native_instr = 0;
        xlat_instr = 0;
        xlat_trap = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); mode = r[0:0];
            r = $random(seed); native_instr = r[31:0];
            r = $random(seed); xlat_instr = r[31:0];
            r = $random(seed); xlat_trap = r[0:0];
            #10;
            if ({d_host_instr, d_trap_out} !== {g_host_instr, g_trap_out}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH interp_fetch_switch32 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS interp_fetch_switch32 lockstep (500 vectors)");
        else $display("FAIL interp_fetch_switch32: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
