// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_scene_player;
    reg clk;
    reg reset;
    reg frame_done;
    reg [7:0] step;
    wire d_gpu_we;
    wire g_gpu_we;
    wire [3:0] d_gpu_addr;
    wire [3:0] g_gpu_addr;
    wire [31:0] d_gpu_wdata;
    wire [31:0] g_gpu_wdata;
    wire [7:0] d_angle;
    wire [7:0] g_angle;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    gpu_scene_player dut(
        .clk(clk),
        .reset(reset),
        .frame_done(frame_done),
        .step(step),
        .gpu_we(d_gpu_we),
        .gpu_addr(d_gpu_addr),
        .gpu_wdata(d_gpu_wdata),
        .angle(d_angle)
    );

    gold_gpu_scene_player gut(
        .clk(clk),
        .reset(reset),
        .frame_done(frame_done),
        .step(step),
        .gpu_we(g_gpu_we),
        .gpu_addr(g_gpu_addr),
        .gpu_wdata(g_gpu_wdata),
        .angle(g_angle)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd13888;
        frame_done = 0;
        step = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); frame_done = r[0:0];
            r = $random(seed); step = r[7:0];
            @(posedge clk); #1;
            if ({d_gpu_we, d_gpu_addr, d_gpu_wdata, d_angle} !== {g_gpu_we, g_gpu_addr, g_gpu_wdata, g_angle}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_scene_player @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_scene_player lockstep (2000 cycles)");
        else $display("FAIL gpu_scene_player: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
