// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_mmio_arbiter2;
    reg a_we;
    reg [3:0] a_addr;
    reg [31:0] a_wdata;
    reg b_we;
    reg [3:0] b_addr;
    reg [31:0] b_wdata;
    wire d_gpu_we;
    wire g_gpu_we;
    wire [3:0] d_gpu_addr;
    wire [3:0] g_gpu_addr;
    wire [31:0] d_gpu_wdata;
    wire [31:0] g_gpu_wdata;
    wire d_b_dropped;
    wire g_b_dropped;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    gpu_mmio_arbiter2 dut(
        .a_we(a_we),
        .a_addr(a_addr),
        .a_wdata(a_wdata),
        .b_we(b_we),
        .b_addr(b_addr),
        .b_wdata(b_wdata),
        .gpu_we(d_gpu_we),
        .gpu_addr(d_gpu_addr),
        .gpu_wdata(d_gpu_wdata),
        .b_dropped(d_b_dropped)
    );

    gold_gpu_mmio_arbiter2 gut(
        .a_we(a_we),
        .a_addr(a_addr),
        .a_wdata(a_wdata),
        .b_we(b_we),
        .b_addr(b_addr),
        .b_wdata(b_wdata),
        .gpu_we(g_gpu_we),
        .gpu_addr(g_gpu_addr),
        .gpu_wdata(g_gpu_wdata),
        .b_dropped(g_b_dropped)
    );

    initial begin
        seed = 32'd36819;
        a_we = 0;
        a_addr = 0;
        a_wdata = 0;
        b_we = 0;
        b_addr = 0;
        b_wdata = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); a_we = r[0:0];
            r = $random(seed); a_addr = r[3:0];
            r = $random(seed); a_wdata = r[31:0];
            r = $random(seed); b_we = r[0:0];
            r = $random(seed); b_addr = r[3:0];
            r = $random(seed); b_wdata = r[31:0];
            #10;
            if ({d_gpu_we, d_gpu_addr, d_gpu_wdata, d_b_dropped} !== {g_gpu_we, g_gpu_addr, g_gpu_wdata, g_b_dropped}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_mmio_arbiter2 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_mmio_arbiter2 lockstep (500 vectors)");
        else $display("FAIL gpu_mmio_arbiter2: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
