// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_bitonic_sort8_8;
    reg [7:0] in0;
    reg [7:0] in1;
    reg [7:0] in2;
    reg [7:0] in3;
    reg [7:0] in4;
    reg [7:0] in5;
    reg [7:0] in6;
    reg [7:0] in7;
    wire [7:0] d_out0;
    wire [7:0] g_out0;
    wire [7:0] d_out1;
    wire [7:0] g_out1;
    wire [7:0] d_out2;
    wire [7:0] g_out2;
    wire [7:0] d_out3;
    wire [7:0] g_out3;
    wire [7:0] d_out4;
    wire [7:0] g_out4;
    wire [7:0] d_out5;
    wire [7:0] g_out5;
    wire [7:0] d_out6;
    wire [7:0] g_out6;
    wire [7:0] d_out7;
    wire [7:0] g_out7;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    bitonic_sort8_8 dut(
        .in0(in0),
        .in1(in1),
        .in2(in2),
        .in3(in3),
        .in4(in4),
        .in5(in5),
        .in6(in6),
        .in7(in7),
        .out0(d_out0),
        .out1(d_out1),
        .out2(d_out2),
        .out3(d_out3),
        .out4(d_out4),
        .out5(d_out5),
        .out6(d_out6),
        .out7(d_out7)
    );

    gold_bitonic_sort8_8 gut(
        .in0(in0),
        .in1(in1),
        .in2(in2),
        .in3(in3),
        .in4(in4),
        .in5(in5),
        .in6(in6),
        .in7(in7),
        .out0(g_out0),
        .out1(g_out1),
        .out2(g_out2),
        .out3(g_out3),
        .out4(g_out4),
        .out5(g_out5),
        .out6(g_out6),
        .out7(g_out7)
    );

    initial begin
        seed = 32'd13257;
        in0 = 0;
        in1 = 0;
        in2 = 0;
        in3 = 0;
        in4 = 0;
        in5 = 0;
        in6 = 0;
        in7 = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); in0 = r[7:0];
            r = $random(seed); in1 = r[7:0];
            r = $random(seed); in2 = r[7:0];
            r = $random(seed); in3 = r[7:0];
            r = $random(seed); in4 = r[7:0];
            r = $random(seed); in5 = r[7:0];
            r = $random(seed); in6 = r[7:0];
            r = $random(seed); in7 = r[7:0];
            #10;
            if ({d_out0, d_out1, d_out2, d_out3, d_out4, d_out5, d_out6, d_out7} !== {g_out0, g_out1, g_out2, g_out3, g_out4, g_out5, g_out6, g_out7}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH bitonic_sort8_8 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS bitonic_sort8_8 lockstep (500 vectors)");
        else $display("FAIL bitonic_sort8_8: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
