// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_dot8;
    reg clk;
    reg reset;
    reg gpu_we;
    reg [3:0] gpu_addr;
    reg [31:0] gpu_wdata;
    reg screen_ready;
    wire [31:0] d_gpu_rdata;
    wire [31:0] g_gpu_rdata;
    wire d_frame_start;
    wire g_frame_start;
    wire d_frame_done;
    wire g_frame_done;
    wire d_enable;
    wire g_enable;
    wire d_fill;
    wire g_fill;
    wire d_mono_valid;
    wire g_mono_valid;
    wire [2:0] d_mono_y;
    wire [2:0] g_mono_y;
    wire [7:0] d_mono_row;
    wire [7:0] g_mono_row;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    gpu_dot8 dut(
        .clk(clk),
        .reset(reset),
        .gpu_we(gpu_we),
        .gpu_addr(gpu_addr),
        .gpu_wdata(gpu_wdata),
        .screen_ready(screen_ready),
        .gpu_rdata(d_gpu_rdata),
        .frame_start(d_frame_start),
        .frame_done(d_frame_done),
        .enable(d_enable),
        .fill(d_fill),
        .mono_valid(d_mono_valid),
        .mono_y(d_mono_y),
        .mono_row(d_mono_row)
    );

    gold_gpu_dot8 gut(
        .clk(clk),
        .reset(reset),
        .gpu_we(gpu_we),
        .gpu_addr(gpu_addr),
        .gpu_wdata(gpu_wdata),
        .screen_ready(screen_ready),
        .gpu_rdata(g_gpu_rdata),
        .frame_start(g_frame_start),
        .frame_done(g_frame_done),
        .enable(g_enable),
        .fill(g_fill),
        .mono_valid(g_mono_valid),
        .mono_y(g_mono_y),
        .mono_row(g_mono_row)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd5806;
        gpu_we = 0;
        gpu_addr = 0;
        gpu_wdata = 0;
        screen_ready = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); gpu_we = r[0:0];
            r = $random(seed); gpu_addr = r[3:0];
            r = $random(seed); gpu_wdata = r[31:0];
            r = $random(seed); screen_ready = r[0:0];
            @(posedge clk); #1;
            if ({d_gpu_rdata, d_frame_start, d_frame_done, d_enable, d_fill, d_mono_valid, d_mono_y, d_mono_row} !== {g_gpu_rdata, g_frame_start, g_frame_done, g_enable, g_fill, g_mono_valid, g_mono_y, g_mono_row}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_dot8 @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_dot8 lockstep (2000 cycles)");
        else $display("FAIL gpu_dot8: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
