// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_reciprocal_seed32;
    reg [31:0] a;
    wire [31:0] d_seed;
    wire [31:0] g_seed;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    reciprocal_seed32 dut(
        .a(a),
        .seed(d_seed)
    );

    gold_reciprocal_seed32 gut(
        .a(a),
        .seed(g_seed)
    );

    initial begin
        seed = 32'd43308;
        a = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); a = r[31:0];
            #10;
            if ({d_seed} !== {g_seed}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH reciprocal_seed32 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS reciprocal_seed32 lockstep (500 vectors)");
        else $display("FAIL reciprocal_seed32: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
