// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_sort4_4;
    reg [3:0] in0;
    reg [3:0] in1;
    reg [3:0] in2;
    reg [3:0] in3;
    wire [3:0] d_out0;
    wire [3:0] g_out0;
    wire [3:0] d_out1;
    wire [3:0] g_out1;
    wire [3:0] d_out2;
    wire [3:0] g_out2;
    wire [3:0] d_out3;
    wire [3:0] g_out3;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    sort4_4 dut(
        .in0(in0),
        .in1(in1),
        .in2(in2),
        .in3(in3),
        .out0(d_out0),
        .out1(d_out1),
        .out2(d_out2),
        .out3(d_out3)
    );

    gold_sort4_4 gut(
        .in0(in0),
        .in1(in1),
        .in2(in2),
        .in3(in3),
        .out0(g_out0),
        .out1(g_out1),
        .out2(g_out2),
        .out3(g_out3)
    );

    initial begin
        seed = 32'd18722;
        in0 = 0;
        in1 = 0;
        in2 = 0;
        in3 = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); in0 = r[3:0];
            r = $random(seed); in1 = r[3:0];
            r = $random(seed); in2 = r[3:0];
            r = $random(seed); in3 = r[3:0];
            #10;
            if ({d_out0, d_out1, d_out2, d_out3} !== {g_out0, g_out1, g_out2, g_out3}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH sort4_4 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS sort4_4 lockstep (500 vectors)");
        else $display("FAIL sort4_4: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
