// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_interp_vonneumann_to_x86_16;
    reg [7:0] host_addr;
    reg [15:0] guest_instr;
    wire [15:0] d_host_instr;
    wire [15:0] g_host_instr;
    wire [3:0] d_guest_addr;
    wire [3:0] g_guest_addr;
    wire d_trap;
    wire g_trap;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    interp_vonneumann_to_x86_16 dut(
        .host_addr(host_addr),
        .guest_instr(guest_instr),
        .host_instr(d_host_instr),
        .guest_addr(d_guest_addr),
        .trap(d_trap)
    );

    gold_interp_vonneumann_to_x86_16 gut(
        .host_addr(host_addr),
        .guest_instr(guest_instr),
        .host_instr(g_host_instr),
        .guest_addr(g_guest_addr),
        .trap(g_trap)
    );

    initial begin
        seed = 32'd5161;
        host_addr = 0;
        guest_instr = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); host_addr = r[7:0];
            r = $random(seed); guest_instr = r[15:0];
            #10;
            if ({d_host_instr, d_guest_addr, d_trap} !== {g_host_instr, g_guest_addr, g_trap}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH interp_vonneumann_to_x86_16 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS interp_vonneumann_to_x86_16 lockstep (500 vectors)");
        else $display("FAIL interp_vonneumann_to_x86_16: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
