// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_cpu_vonneumann32;
    reg clk;
    reg rst;
    reg run;
    reg prog_we;
    reg [3:0] prog_addr;
    reg [31:0] prog_data;
    wire [31:0] d_out_data;
    wire [31:0] g_out_data;
    wire d_out_valid;
    wire g_out_valid;
    wire d_halted;
    wire g_halted;
    wire [31:0] d_dbg_acc;
    wire [31:0] g_dbg_acc;
    wire [3:0] d_dbg_pc;
    wire [3:0] g_dbg_pc;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    cpu_vonneumann32 dut(
        .clk(clk),
        .rst(rst),
        .run(run),
        .prog_we(prog_we),
        .prog_addr(prog_addr),
        .prog_data(prog_data),
        .out_data(d_out_data),
        .out_valid(d_out_valid),
        .halted(d_halted),
        .dbg_acc(d_dbg_acc),
        .dbg_pc(d_dbg_pc)
    );

    gold_cpu_vonneumann32 gut(
        .clk(clk),
        .rst(rst),
        .run(run),
        .prog_we(prog_we),
        .prog_addr(prog_addr),
        .prog_data(prog_data),
        .out_data(g_out_data),
        .out_valid(g_out_valid),
        .halted(g_halted),
        .dbg_acc(g_dbg_acc),
        .dbg_pc(g_dbg_pc)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd62176;
        run = 0;
        prog_we = 0;
        prog_addr = 0;
        prog_data = 0;
        rst = 1;
        repeat (5) @(posedge clk);
        rst = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); run = r[0:0];
            r = $random(seed); prog_we = r[0:0];
            r = $random(seed); prog_addr = r[3:0];
            r = $random(seed); prog_data = r[31:0];
            @(posedge clk); #1;
            if ({d_out_data, d_out_valid, d_halted, d_dbg_acc, d_dbg_pc} !== {g_out_data, g_out_valid, g_halted, g_dbg_acc, g_dbg_pc}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH cpu_vonneumann32 @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS cpu_vonneumann32 lockstep (2000 cycles)");
        else $display("FAIL cpu_vonneumann32: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
