// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_add_ling8;
    reg [7:0] a;
    reg [7:0] b;
    reg cin;
    wire [7:0] d_sum;
    wire [7:0] g_sum;
    wire d_cout;
    wire g_cout;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    add_ling8 dut(
        .a(a),
        .b(b),
        .cin(cin),
        .sum(d_sum),
        .cout(d_cout)
    );

    gold_add_ling8 gut(
        .a(a),
        .b(b),
        .cin(cin),
        .sum(g_sum),
        .cout(g_cout)
    );

    initial begin
        seed = 32'd24046;
        a = 0;
        b = 0;
        cin = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); a = r[7:0];
            r = $random(seed); b = r[7:0];
            r = $random(seed); cin = r[0:0];
            #10;
            if ({d_sum, d_cout} !== {g_sum, g_cout}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH add_ling8 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS add_ling8 lockstep (500 vectors)");
        else $display("FAIL add_ling8: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
