// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_bitonic_sort16_8;
    reg [7:0] in0;
    reg [7:0] in1;
    reg [7:0] in2;
    reg [7:0] in3;
    reg [7:0] in4;
    reg [7:0] in5;
    reg [7:0] in6;
    reg [7:0] in7;
    reg [7:0] in8;
    reg [7:0] in9;
    reg [7:0] in10;
    reg [7:0] in11;
    reg [7:0] in12;
    reg [7:0] in13;
    reg [7:0] in14;
    reg [7:0] in15;
    wire [7:0] d_out0;
    wire [7:0] g_out0;
    wire [7:0] d_out1;
    wire [7:0] g_out1;
    wire [7:0] d_out2;
    wire [7:0] g_out2;
    wire [7:0] d_out3;
    wire [7:0] g_out3;
    wire [7:0] d_out4;
    wire [7:0] g_out4;
    wire [7:0] d_out5;
    wire [7:0] g_out5;
    wire [7:0] d_out6;
    wire [7:0] g_out6;
    wire [7:0] d_out7;
    wire [7:0] g_out7;
    wire [7:0] d_out8;
    wire [7:0] g_out8;
    wire [7:0] d_out9;
    wire [7:0] g_out9;
    wire [7:0] d_out10;
    wire [7:0] g_out10;
    wire [7:0] d_out11;
    wire [7:0] g_out11;
    wire [7:0] d_out12;
    wire [7:0] g_out12;
    wire [7:0] d_out13;
    wire [7:0] g_out13;
    wire [7:0] d_out14;
    wire [7:0] g_out14;
    wire [7:0] d_out15;
    wire [7:0] g_out15;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    bitonic_sort16_8 dut(
        .in0(in0),
        .in1(in1),
        .in2(in2),
        .in3(in3),
        .in4(in4),
        .in5(in5),
        .in6(in6),
        .in7(in7),
        .in8(in8),
        .in9(in9),
        .in10(in10),
        .in11(in11),
        .in12(in12),
        .in13(in13),
        .in14(in14),
        .in15(in15),
        .out0(d_out0),
        .out1(d_out1),
        .out2(d_out2),
        .out3(d_out3),
        .out4(d_out4),
        .out5(d_out5),
        .out6(d_out6),
        .out7(d_out7),
        .out8(d_out8),
        .out9(d_out9),
        .out10(d_out10),
        .out11(d_out11),
        .out12(d_out12),
        .out13(d_out13),
        .out14(d_out14),
        .out15(d_out15)
    );

    gold_bitonic_sort16_8 gut(
        .in0(in0),
        .in1(in1),
        .in2(in2),
        .in3(in3),
        .in4(in4),
        .in5(in5),
        .in6(in6),
        .in7(in7),
        .in8(in8),
        .in9(in9),
        .in10(in10),
        .in11(in11),
        .in12(in12),
        .in13(in13),
        .in14(in14),
        .in15(in15),
        .out0(g_out0),
        .out1(g_out1),
        .out2(g_out2),
        .out3(g_out3),
        .out4(g_out4),
        .out5(g_out5),
        .out6(g_out6),
        .out7(g_out7),
        .out8(g_out8),
        .out9(g_out9),
        .out10(g_out10),
        .out11(g_out11),
        .out12(g_out12),
        .out13(g_out13),
        .out14(g_out14),
        .out15(g_out15)
    );

    initial begin
        seed = 32'd16847;
        in0 = 0;
        in1 = 0;
        in2 = 0;
        in3 = 0;
        in4 = 0;
        in5 = 0;
        in6 = 0;
        in7 = 0;
        in8 = 0;
        in9 = 0;
        in10 = 0;
        in11 = 0;
        in12 = 0;
        in13 = 0;
        in14 = 0;
        in15 = 0;
        for (i = 0; i < 500; i = i + 1) begin
            r = $random(seed); in0 = r[7:0];
            r = $random(seed); in1 = r[7:0];
            r = $random(seed); in2 = r[7:0];
            r = $random(seed); in3 = r[7:0];
            r = $random(seed); in4 = r[7:0];
            r = $random(seed); in5 = r[7:0];
            r = $random(seed); in6 = r[7:0];
            r = $random(seed); in7 = r[7:0];
            r = $random(seed); in8 = r[7:0];
            r = $random(seed); in9 = r[7:0];
            r = $random(seed); in10 = r[7:0];
            r = $random(seed); in11 = r[7:0];
            r = $random(seed); in12 = r[7:0];
            r = $random(seed); in13 = r[7:0];
            r = $random(seed); in14 = r[7:0];
            r = $random(seed); in15 = r[7:0];
            #10;
            if ({d_out0, d_out1, d_out2, d_out3, d_out4, d_out5, d_out6, d_out7, d_out8, d_out9, d_out10, d_out11, d_out12, d_out13, d_out14, d_out15} !== {g_out0, g_out1, g_out2, g_out3, g_out4, g_out5, g_out6, g_out7, g_out8, g_out9, g_out10, g_out11, g_out12, g_out13, g_out14, g_out15}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH bitonic_sort16_8 @vector %0d", i);
            end
        end
        if (errors == 0) $display("PASS bitonic_sort16_8 lockstep (500 vectors)");
        else $display("FAIL bitonic_sort16_8: %0d mismatching vectors", errors);
        $finish;
    end
endmodule
