// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_cpu_stack8;
    reg clk;
    reg rst;
    reg [15:0] imem_data;
    wire [7:0] d_imem_addr;
    wire [7:0] g_imem_addr;
    wire [7:0] d_out_data;
    wire [7:0] g_out_data;
    wire d_out_valid;
    wire g_out_valid;
    wire d_halted;
    wire g_halted;
    wire [7:0] d_dbg_tos;
    wire [7:0] g_dbg_tos;
    wire [4:0] d_dbg_depth;
    wire [4:0] g_dbg_depth;
    wire [7:0] d_dbg_pc;
    wire [7:0] g_dbg_pc;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    cpu_stack8 dut(
        .clk(clk),
        .rst(rst),
        .imem_data(imem_data),
        .imem_addr(d_imem_addr),
        .out_data(d_out_data),
        .out_valid(d_out_valid),
        .halted(d_halted),
        .dbg_tos(d_dbg_tos),
        .dbg_depth(d_dbg_depth),
        .dbg_pc(d_dbg_pc)
    );

    gold_cpu_stack8 gut(
        .clk(clk),
        .rst(rst),
        .imem_data(imem_data),
        .imem_addr(g_imem_addr),
        .out_data(g_out_data),
        .out_valid(g_out_valid),
        .halted(g_halted),
        .dbg_tos(g_dbg_tos),
        .dbg_depth(g_dbg_depth),
        .dbg_pc(g_dbg_pc)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd9016;
        imem_data = 0;
        rst = 1;
        repeat (5) @(posedge clk);
        rst = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); imem_data = r[15:0];
            @(posedge clk); #1;
            if ({d_imem_addr, d_out_data, d_out_valid, d_halted, d_dbg_tos, d_dbg_depth, d_dbg_pc} !== {g_imem_addr, g_out_data, g_out_valid, g_halted, g_dbg_tos, g_dbg_depth, g_dbg_pc}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH cpu_stack8 @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS cpu_stack8 lockstep (2000 cycles)");
        else $display("FAIL cpu_stack8: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
