// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_frame_pacer;
    reg clk;
    reg reset;
    reg [15:0] rate;
    reg frame_start;
    reg frame_done;
    wire d_screen_ready;
    wire g_screen_ready;
    wire [15:0] d_frame_count;
    wire [15:0] g_frame_count;
    wire d_frame_tick;
    wire g_frame_tick;
    wire d_in_frame;
    wire g_in_frame;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [63:0] rr;
    initial errors = 0;

    gpu_frame_pacer dut(
        .clk(clk),
        .reset(reset),
        .rate(rate),
        .frame_start(frame_start),
        .frame_done(frame_done),
        .screen_ready(d_screen_ready),
        .frame_count(d_frame_count),
        .frame_tick(d_frame_tick),
        .in_frame(d_in_frame)
    );

    gold_gpu_frame_pacer gut(
        .clk(clk),
        .reset(reset),
        .rate(rate),
        .frame_start(frame_start),
        .frame_done(frame_done),
        .screen_ready(g_screen_ready),
        .frame_count(g_frame_count),
        .frame_tick(g_frame_tick),
        .in_frame(g_in_frame)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd21665;
        rate = 0;
        frame_start = 0;
        frame_done = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); rate = r[15:0];
            r = $random(seed); frame_start = r[0:0];
            r = $random(seed); frame_done = r[0:0];
            @(posedge clk); #1;
            if ({d_screen_ready, d_frame_count, d_frame_tick, d_in_frame} !== {g_screen_ready, g_frame_count, g_frame_tick, g_in_frame}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_frame_pacer @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_frame_pacer lockstep (2000 cycles)");
        else $display("FAIL gpu_frame_pacer: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
