// auto-generated by scripts/gen_lockstep.py -- do not edit
`timescale 1ns/1ps
module tb_ls_gpu_row_to_pixel;
    reg clk;
    reg reset;
    reg [7:0] w_field;
    reg mono_valid;
    reg [7:0] mono_y;
    reg [63:0] mono_s0;
    reg [63:0] mono_s1;
    reg [63:0] mono_s2;
    reg [63:0] mono_s3;
    reg px_ready;
    wire d_row_ready;
    wire g_row_ready;
    wire d_px_valid;
    wire g_px_valid;
    wire [7:0] d_px_x;
    wire [7:0] g_px_x;
    wire [7:0] d_px_y;
    wire [7:0] g_px_y;
    wire d_px_on;
    wire g_px_on;
    integer i, errors;
    integer seed;
    reg [31:0] r;
    reg [127:0] rr;
    initial errors = 0;

    gpu_row_to_pixel dut(
        .clk(clk),
        .reset(reset),
        .w_field(w_field),
        .mono_valid(mono_valid),
        .mono_y(mono_y),
        .mono_s0(mono_s0),
        .mono_s1(mono_s1),
        .mono_s2(mono_s2),
        .mono_s3(mono_s3),
        .px_ready(px_ready),
        .row_ready(d_row_ready),
        .px_valid(d_px_valid),
        .px_x(d_px_x),
        .px_y(d_px_y),
        .px_on(d_px_on)
    );

    gold_gpu_row_to_pixel gut(
        .clk(clk),
        .reset(reset),
        .w_field(w_field),
        .mono_valid(mono_valid),
        .mono_y(mono_y),
        .mono_s0(mono_s0),
        .mono_s1(mono_s1),
        .mono_s2(mono_s2),
        .mono_s3(mono_s3),
        .px_ready(px_ready),
        .row_ready(g_row_ready),
        .px_valid(g_px_valid),
        .px_x(g_px_x),
        .px_y(g_px_y),
        .px_on(g_px_on)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        seed = 32'd34512;
        w_field = 0;
        mono_valid = 0;
        mono_y = 0;
        mono_s0 = 0;
        mono_s1 = 0;
        mono_s2 = 0;
        mono_s3 = 0;
        px_ready = 0;
        reset = 1;
        repeat (5) @(posedge clk);
        reset = 0;
        for (i = 0; i < 2000; i = i + 1) begin
            @(negedge clk);
            r = $random(seed); w_field = r[7:0];
            r = $random(seed); mono_valid = r[0:0];
            r = $random(seed); mono_y = r[7:0];
            r = $random(seed); rr[31:0] = r;
            r = $random(seed); rr[63:32] = r;
            mono_s0 = rr[63:0];
            r = $random(seed); rr[31:0] = r;
            r = $random(seed); rr[63:32] = r;
            mono_s1 = rr[63:0];
            r = $random(seed); rr[31:0] = r;
            r = $random(seed); rr[63:32] = r;
            mono_s2 = rr[63:0];
            r = $random(seed); rr[31:0] = r;
            r = $random(seed); rr[63:32] = r;
            mono_s3 = rr[63:0];
            r = $random(seed); px_ready = r[0:0];
            @(posedge clk); #1;
            if ({d_row_ready, d_px_valid, d_px_x, d_px_y, d_px_on} !== {g_row_ready, g_px_valid, g_px_x, g_px_y, g_px_on}) begin
                errors = errors + 1;
                if (errors <= 5)
                    $display("MISMATCH gpu_row_to_pixel @cycle %0d", i);
            end
        end
        if (errors == 0) $display("PASS gpu_row_to_pixel lockstep (2000 cycles)");
        else $display("FAIL gpu_row_to_pixel: %0d mismatching cycles", errors);
        $finish;
    end
endmodule
